### ISSUE TITLE
BTN _get_season_search_strings() API call error. (More arguments given than expected)

### ISSUE THREAD

**Issue by Apocrathia** [lad1337/Sick-Beard#5]
Posted on the SickBeard bugtracker and was redirected here.

Before posting a bug be sure you have posted ALL of the following
information:

1) What were you doing when you encountered the problem? Post show/episode,
URL, what links you clicked, what you did immediately before, related Sick
Beard settings, etc.

N/a

2) Post the Python traceback from the HTTP server or python console.

N/a

3) Attach your log file and indicate the approximate timestamp where the
error occured.

2013-07-07 00:00:34.010710 SEARCHQUEUE-BACKLOG-75411 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 00:00:34.723571 SEARCHQUEUE-BACKLOG-195571 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 00:00:40.053981 SEARCHQUEUE-BACKLOG-266581 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 01:00:34.135965 FINDPROPERS :: Exception generated in thread FINDPROPERS: Element instance has no attribute 'findtext'
2013-07-07 03:01:26.632699 SHOWQUEUE-REFRESH :: Multiple episodes for a absolute number. this might happend because we are missing a scene name for this season. xem lacking behind ?
2013-07-07 03:01:26.632830 SHOWQUEUE-REFRESH :: Error during parsing. Error will raise again. traceback:
2013-07-07 03:01:26.636324 SHOWQUEUE-REFRESH :: Traceback (most recent call last): File "/Users/ianyoung/Sites/MyAnime/sickbeard/completparser.py", line 63, in parse result = self._parse(name_to_parse) File "/Users/*****_/Sites/MyAnime/sickbeard/completparser.py", line 117, in _parse self.scene2tvdb(cur_show, self.raw_parse_result.series_name, self.raw_parse_result.season_number, self.raw_parse_result.episode_numbers, self.raw_parse_result.ab_episode_numbers) File "/Users/**_***/Sites/MyAnime/sickbeard/completparser.py", line 287, in scene2tvdb raise MultipleSceneEpisodeResults("Multiple episodes for a absolute number") MultipleSceneEpisodeResults: Multiple episodes for a absolute number 
2013-07-07 12:00:30.782334 SEARCHQUEUE-BACKLOG-75411 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 12:00:45.358967 SEARCHQUEUE-BACKLOG-195571 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 12:00:51.958023 SEARCHQUEUE-BACKLOG-266581 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 18:10:51.030686 SEARCHQUEUE-BACKLOG-78856 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)
2013-07-07 18:14:17.673625 SEARCHQUEUE-BACKLOG-78856 :: Error while searching BTN, skipping: _get_season_search_strings() takes at most 3 arguments (4 given)

4) Indicate the version/revision you're running and which OS.

OS X 10.8.4. Pulling latest code via github every night from anime-development branch.

The bug will NOT get fixed unless I can figure out what the problem is, so
the more information the better.

from what I can tell, it just seems to be an issue with the _get_season-search_strings() API call for broadcasthe.net. I'm having to go manually fetch some of the files I'm missing.

**Comment by Apocrathia** [comment]
I don't even use this anymore. Doing some housekeeping.
